import { ClipboardList, Clock4, GitBranch, Sparkles, Target, Trophy, UsersRound, Brain, ArchiveRestore, Award } from 'lucide-react';
import { useScrollReveal } from '../hooks/useScrollReveal';

const arwaPhoto = new URL('../../pictures/arwa.jpeg', import.meta.url).href;
const fatimaPhoto = new URL('../../pictures/fatima.jpeg', import.meta.url).href;
const tahaPhoto = new URL('../../pictures/taha.jpeg', import.meta.url).href;

const teamMembers = [
  {
    name: 'Arwa Javed',
    role: 'Project Lead · Discrete Structures',
    statement:
      'Arwa reframed Pakistan\'s market-integration challenge as a layered graph + poset problem, giving the submission its mathematical spine.',
    contributions: [
      'Authored the proofs that guaranteed reflexivity, antisymmetry, and transitivity every month.',
      'Mapped each visualization to the theorem or lemma cited inside the final report.',
      'Led reviewer walk-throughs so discrete math insights landed with non-technical stakeholders.'
    ],
    focus: 'Guaranteeing the mathematical soundness of every inference.',
    photo: arwaPhoto
  },
  {
    name: 'Fatima Hashmat',
    role: 'Data Engineering · Backend Pipeline',
    statement:
      'Fatima owned ingestion, similarity engines, and the automation that produced every CSV, PNG, and checksum in the Submission Package.',
    contributions: [
      'Staged PBS PDFs/XLSX files into normalized monthly tables ready for weighting.',
      'Implemented entropy + stakeholder weighting modes with reproducible seeds.',
      'Versioned config.yaml and run logs so auditors can replay each export.'
    ],
    focus: 'Keeping the analytical engine deterministic and auditable.',
    photo: fatimaPhoto
  },
  {
    name: 'Muhammad Taha Nasim',
    role: 'Visualization · Frontend Systems',
    statement:
      'Taha translated dense network metrics into an immersive dashboard, matching the neon observatory aesthetic across every surface.',
    contributions: [
      'Built the force-directed canvas, timeline scrubber, and fullscreen narrative states in React.',
      'Crafted Submission Atlas cards + animations to mirror backend provenance.',
      'Owned accessibility and performance budgets so the site stayed fluid on mid-tier hardware.'
    ],
    focus: 'Translating analytics into intuitive storytelling.',
    photo: tahaPhoto
  }
];

const collaborationPillars = [
  {
    label: 'Weekly Syncs',
    description: 'Standing architecture & synthesis sessions with live demo checkpoints.'
  },
  {
    label: 'Version Discipline',
    description: 'Git-based release gates; no visualization change ships without matching report notes.'
  },
  {
    label: 'Peer Review',
    description: 'Cross-functional review matrix—data engineers audit UI states, designers read pipelines.'
  },
  {
    label: 'Stakeholder Loops',
    description: 'Bi-weekly dry runs with faculty mentors for early feedback on insights.'
  }
];

const deliveryLedger = [
  {
    title: 'Artifact Sprint → Submission_Package/1.Executive_Summary_Visuals',
    detail:
      'Taha partnered with Arwa to align captions and overlays, exporting 12 PNGs in both 4K and lightweight variants so the visuals matched the storyboards in Project_Report.docx.'
  },
  {
    title: 'Pipeline Hardening → Submission_Package/3.Source_Code',
    detail:
      'Fatima froze preprocessing scripts, tagged commit hashes inside config.yaml, and dropped the exact code bundle auditors now use to reproduce similarity matrices.'
  },
  {
    title: 'Policy Translation → Submission_Package/2.Final_Report_Documents',
    detail:
      'Arwa authored the methodology + stakeholder response sections, aligning every chart reference with the numbering system inside Final_Rankings_Summary.xlsx.'
  },
  {
    title: 'Evidence Lockbox → Submission_Package/4.Analysis_Output_Archive',
    detail:
      'Arwa, Fatima, and Taha validated that each CSV/PNG generated by the pipeline had a checksum logged before being zipped, giving reviewers full traceability from raw data to dashboards.'
  }
];

const cadenceMoments = [
  {
    stamp: 'Mondays · 09:00',
    description: 'Architecture council—review PBS deltas, approve new config.yaml parameters, and schedule pipeline runs.',
    icon: Clock4
  },
  {
    stamp: 'Wednesdays · 14:00',
    description: 'Visualization lab—screen-share latest `src/pages/VisualizationPage.tsx` builds and fine-tune animations.',
    icon: Trophy
  },
  {
    stamp: 'Fridays · 17:00',
    description: 'Submission huddle—update Submission_Package manifests, verify README snippets, and rehearse narrative beats.',
    icon: ClipboardList
  }
];

export default function TeamPage() {
  const heroRef = useScrollReveal<HTMLElement>({ threshold: 0.05 });
  const membersRef = useScrollReveal<HTMLElement>();
  const collaborationRef = useScrollReveal<HTMLElement>();
  const ledgerRef = useScrollReveal<HTMLElement>();

  return (
    <div className="bg-[#01050F] text-slate-100 min-h-screen">
      <section
        ref={heroRef}
        className="group reveal relative overflow-hidden border-b border-white/5 px-6 py-16"
      >
        <div className="absolute inset-0 opacity-40 pointer-events-none">
          <div className="absolute left-1/2 top-0 h-64 w-64 -translate-x-1/2 rounded-full bg-purple-500/30 blur-[160px]" />
        </div>
        <div className="relative z-10 max-w-4xl mx-auto text-center space-y-6">
          <p className="inline-flex items-center gap-2 rounded-full border border-white/10 px-4 py-1 font-mono text-xs uppercase tracking-[0.3em] text-cyan-200">
            <UsersRound className="h-3.5 w-3.5" /> Core Contributors
          </p>
          <h1 className="text-4xl md:text-5xl font-black text-white">People behind the observatory</h1>
          <p className="text-lg text-slate-300">
            A women-led research and engineering duo—Arwa on discrete math, Fatima on pipelines—paired with Taha on visualization.
            Together they ran synchronized demos, dataset diffs, and storytelling rehearsals every sprint.
          </p>
        </div>
      </section>

      <section
        ref={membersRef}
        className="group reveal max-w-6xl mx-auto px-6 py-20 space-y-20"
      >
        {teamMembers.map((member, idx) => {
          const isReversed = idx % 2 === 1;
          return (
            <article
              key={member.name}
              className={`opacity-0 translate-y-8 group-data-[visible=true]:opacity-100 group-data-[visible=true]:translate-y-0 transition-all duration-700`}
              style={{ transitionDelay: `${160 + idx * 160}ms` }}
            >
              <div
                className={`flex flex-col gap-10 md:gap-16 md:items-center ${
                  isReversed ? 'md:flex-row-reverse' : 'md:flex-row'
                }`}
              >
                <div className="flex justify-center md:w-1/2">
                  <img
                    src={member.photo}
                    alt={`${member.name} portrait`}
                    className="h-60 w-60 sm:h-72 sm:w-72 md:h-80 md:w-80 rounded-[40px] object-cover shadow-[0_30px_70px_rgba(6,182,212,0.35)] border border-white/10"
                    loading="lazy"
                  />
                </div>
                <div className="md:w-1/2 space-y-6 text-left">
                  <div>
                    <p className="text-xs uppercase tracking-[0.4em] text-cyan-200 flex items-center gap-2">
                      <Award className="h-4 w-4 text-lime-300" />
                      {member.role}
                    </p>
                    <h2 className="mt-3 text-3xl font-black text-white">{member.name}</h2>
                  </div>
                  <p className="text-base text-slate-200 leading-relaxed">{member.statement}</p>
                  <p className="text-sm text-slate-400 font-mono">{member.focus}</p>
                  <ul className="space-y-3 text-sm text-slate-100">
                    {member.contributions.map((point) => (
                      <li key={point} className="flex items-start gap-3">
                        <Target className="mt-1 h-4 w-4 text-lime-300" />
                        <span>{point}</span>
                      </li>
                    ))}
                  </ul>
                </div>
              </div>
            </article>
          );
        })}
      </section>

      <section
        ref={collaborationRef}
        className="group reveal bg-black/40 border-y border-white/5 px-6 py-16"
      >
        <div className="max-w-6xl mx-auto grid gap-10 md:grid-cols-[1.2fr,0.8fr]">
          <div>
            <div className="flex items-center gap-3 text-cyan-400 font-semibold uppercase tracking-[0.2em] text-xs">
              <Sparkles className="h-4 w-4" /> Collaboration DNA
            </div>
            <h2 className="mt-4 text-3xl font-bold text-white">How we kept momentum</h2>
            <div className="mt-8 grid gap-6 md:grid-cols-2">
              {collaborationPillars.map((pillar) => (
                <div key={pillar.label} className="glow-card rounded-2xl p-5">
                  <p className="text-xs uppercase tracking-[0.3em] text-slate-400">{pillar.label}</p>
                  <p className="mt-3 text-sm text-slate-200 leading-relaxed">{pillar.description}</p>
                </div>
              ))}
            </div>
          </div>
          <div className="glow-card rounded-3xl p-6 space-y-6">
            <div>
              <p className="text-xs uppercase tracking-[0.3em] text-slate-400">Toolchain Spotlight</p>
              <ul className="mt-4 space-y-2 text-sm text-slate-200">
                <li className="flex items-center gap-2">
                  <GitBranch className="h-4 w-4 text-cyan-300" /> Git + Conventional commits
                </li>
                <li className="flex items-center gap-2">
                  <Brain className="h-4 w-4 text-pink-300" /> Notion research sprints
                </li>
                <li className="flex items-center gap-2">
                  <UsersRound className="h-4 w-4 text-purple-300" /> Figma journey boards
                </li>
                <li className="flex items-center gap-2">
                  <Award className="h-4 w-4 text-amber-300" /> QA scorecards mapped to rubric
                </li>
              </ul>
            </div>
            <div>
              <p className="text-xs uppercase tracking-[0.3em] text-slate-400">Thank you</p>
              <p className="mt-3 text-sm text-slate-300">
                Mentors from the Discrete Mathematics lab and the Economic Policy faculty guided us with review clinics
                and supplied annotated CPI digests. Their feedback loops shaped the final polish you see today.
              </p>
            </div>
          </div>
        </div>
      </section>

      <section
        ref={ledgerRef}
        className="group reveal px-6 py-16 border-t border-white/5 bg-gradient-to-b from-[#030A1E] to-[#010409]"
      >
        <div className="max-w-6xl mx-auto grid gap-10 md:grid-cols-[1.4fr,0.6fr]">
          <div>
            <div className="flex items-center gap-3 text-cyan-400 font-semibold uppercase tracking-[0.2em] text-xs">
              <ArchiveRestore className="h-4 w-4" /> Submission Hand-Off Ledger
            </div>
            <h2 className="mt-4 text-3xl font-bold text-white">How every deliverable moved from code to archive</h2>
            <p className="mt-4 text-sm text-slate-300 leading-relaxed">
              Scroll auditors asked for “minute detailing” of the people behind each folder inside `Submission_Package`.
              This ledger captures those hand-offs so it is obvious who shepherded visuals, reports, pipelines, and
              archives into their final homes.
            </p>
            <ul className="mt-8 space-y-5">
              {deliveryLedger.map((entry, idx) => (
                <li
                  key={entry.title}
                  className="glow-card rounded-2xl p-5 opacity-0 translate-y-8 group-data-[visible=true]:opacity-100 group-data-[visible=true]:translate-y-0 transition-all duration-700"
                  style={{ transitionDelay: `${180 + idx * 110}ms` }}
                >
                  <p className="text-xs font-mono uppercase tracking-[0.3em] text-slate-400">{entry.title}</p>
                  <p className="mt-3 text-sm text-slate-200 leading-relaxed">{entry.detail}</p>
                </li>
              ))}
            </ul>
          </div>
          <div className="rounded-3xl border border-white/10 bg-white/5 p-6 space-y-6">
            <div>
              <p className="text-xs uppercase tracking-[0.3em] text-slate-400 flex items-center gap-2">
                <GitBranch className="h-4 w-4 text-cyan-300" /> Ritual Cadence
              </p>
              <ul className="mt-4 space-y-3 text-sm text-slate-200">
                {cadenceMoments.map((moment, idx) => (
                  <li
                    key={moment.stamp}
                    className="flex items-start gap-3 opacity-0 translate-y-6 group-data-[visible=true]:opacity-100 group-data-[visible=true]:translate-y-0 transition-all duration-700"
                    style={{ transitionDelay: `${200 + idx * 120}ms` }}
                  >
                    <moment.icon className="mt-1 h-4 w-4 text-cyan-300" />
                    <div>
                      <p className="font-semibold text-white">{moment.stamp}</p>
                      <p className="text-slate-300">{moment.description}</p>
                    </div>
                  </li>
                ))}
              </ul>
            </div>
            <div>
              <p className="text-xs uppercase tracking-[0.3em] text-slate-400 flex items-center gap-2">
                <Trophy className="h-4 w-4 text-amber-300" /> Mentorship Callouts
              </p>
              <p className="mt-3 text-sm text-slate-300">
                Discrete Mathematics faculty stress-tested our Hasse proofs, while Economic Policy mentors rehearsed the
                briefings that accompany `Submission_Package/2.Final_Report_Documents`. Their annotations are logged in the
                README so future cohorts can trace our decision trail.
              </p>
            </div>
          </div>
        </div>
      </section>
    </div>
  );
}


